### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by nglseries** [TrvsF/discord-token-logger#10]
How do i download these type of stuff.

**Comment by YeahOMA** [comment]
You have to have a brain first of all.

Putting backdoors into your clients source code and distributing them is a serious federal offense and can land you in jail along with a few several thousand dollar fine. How retarded are you though. 

Contact me - ThatOMA#6969

**Comment by TrvsF** [comment]
the person above is mostly wrong, but you still probably dont want to
