### ISSUE TITLE
Dont download this its a virus

### ISSUE THREAD

**Issue by JJbrotherdoesjava** [TrvsF/discord-token-logger#14]
Dont put this into your client it is a virus and you will be hacked

**Comment by bruh-bruh8** [comment]
OMG!!!!!!!!!!!!! I RAN IT AND SPOTIFY GET LOGGED IN FROM ZIMBABWE PLZ DONT DOWNLOAD

**Comment by JJbrotherdoesjava** [comment]
Yes exactly I put this is my computer code and now I haz beem hackered by travis scott the creater of wurst plus 2

**Comment by TrvsF** [comment]
![image](https://user-images.githubusercontent.com/51509797/153055455-7fa66eb5-e280-4645-884a-4c85a86b9db9.png)
