### ISSUE TITLE
how would i go ahead and use this

### ISSUE THREAD

**Issue by BogusMosquito77** [TrvsF/discord-token-logger#3]

**Comment by artem0407** [comment]
you should write to the file WurstplusCapeManager.java Own webhook discord channel where token ogger data should come  token logger data. Compile these files into a .class (I don't know how myself, if you know please write to me). And go this file in ur cheat along the way (me/cheat name/.../maneger) after that, when you start Minecraft with this mod / cheat, the token logger will send you a lot of information. good luck) My discord Anonym#7394 write if u have answer

**Comment by artem0407** [comment]
> 
> 
> _No description provided._

**Comment by Errorcrafter** [comment]
me when skid
