### ISSUE TITLE
Ignore this I'm an idiot

### ISSUE THREAD

**Issue by proudmuslim-dev** [TrvsF/discord-token-logger#4]

**Comment by TrvsF** [comment]
unsure what you mean by 'illegal data' but please refer the first line in the readme were it says 'this is to spread awareness' for the rest of your worries

**Comment by proudmuslim-dev** [comment]
My apologies, I came across this repo because I found this exact code in a malicious mod being distributed and didn't bother to see the readme. It was my own stupidity and lack of attention, sorry about that
