### ISSUE TITLE
how do i add my webhook to this

### ISSUE THREAD

**Issue by AstroOrbis** [TrvsF/discord-token-logger#5]

**Comment by TheAlphaEpsilon** [comment]
you are dumb and/or stupid

**Comment by artem0407** [comment]
1)Go to settings discord channel 
2)Go to integration 
3)Go to webhook
4)Copy ur webhook
5)Go to WursPlusCapeManager
6)Paste ur webhook in special place (i dont remember where)

**Comment by AstroOrbis** [comment]
Thanks!

**Comment by artem0407** [comment]
> Благодарность!

No problem, if you have any questions, write in discord:  Anonym#7394

**Comment by czho** [comment]
I mean he's smart enough to know what webhooks are but not smart enough to literally admit to trying to use a token logger on other ppl.

**Comment by AstroOrbis** [comment]
i want to use it to pranx my friends lol

also what do i do with the files after?

**Comment by laika-cosmonaut** [comment]
what a retard, you put them in your mod

**Comment by AstroOrbis** [comment]
> what a retard, you put them in your mod

Bro just chill, ok

**Comment by AstroOrbis** [comment]
all of the files?

**Comment by TrvsF** [comment]
this isn't the place to discuss how to token log people.

**Comment by AstroOrbis** [comment]
im just asking
