### ISSUE TITLE
Retard alert!

### ISSUE THREAD

**Issue by Monchy-jar** [TrvsF/discord-token-logger#6]
The only reason why your gay ass theia says that this is a token logger is because the web connections, the connections you got here are connections to THE CAPE SERVERS AND THINGS THAT NEED TO CONNECT TO THE INTERNET. w+2 is safe if its not the one you get from crystallinqq

**Comment by TrvsF** [comment]
what

**Comment by Mskeen000** [comment]
Im reading old shits and im so confused

**Comment by Tripiii** [comment]
> Im reading old shits and im so confused
> 
> 

Same lmao
