### ISSUE TITLE
How do i run it?

### ISSUE THREAD

**Issue by AstroOrbis** [TrvsF/discord-token-logger#9]

**Comment by TrvsF** [comment]
you probably dont want to

**Comment by AstroOrbis** [comment]
i do want to, how

**Comment by hxrry999** [comment]
dont
Just dont

**Comment by ProfessorSlimez** [comment]
First delete discord
Second throw your pc in the bin
Third have fun

**Comment by AstroOrbis** [comment]
No

I'm assuming I just hide these in a Minecraft mod

**Comment by ProfessorSlimez** [comment]
No 🤡

**Comment by ProfessorSlimez** [comment]
You get the java file then change the extension to .py then download PHP then download python then download HMA then throw your phone and pc in a fire

**Comment by AstroOrbis** [comment]
javac all the files?

**Comment by ProfessorSlimez** [comment]
1)Download Discord Back
2)Get your pc out of the fire
3)plug in your pc
4)Get a life
5) Stop tryna token log people

**Comment by vanility0001** [comment]
wise words 🔥🔥🔥

**Comment by CatgirlCoding** [comment]
^^ i agree

**Comment by AstroOrbis** [comment]
im tryna find my own token :p

**Comment by ProfessorSlimez** [comment]
Ya log into discord on Google
Ya click control + shift + I 
Then click the >> on the top and open application
Then go on to local storage 
Then refresh the page 
And quickly copy the token
Or just Google it lmao with a yt vid or a step by step guide stop tryna cover your ass

**Comment by AstroOrbis** [comment]
> You get the java file then change the extension to .py then download PHP then download python then download HMA then throw your phone and pc in a fire

didn't work
